server:
  port: 8090

ribbon:
  IsSecure: false

security:
  basic:
    enabled: false

management:
  security:
    enabled: false

---

spring:
  profiles: default

security:
  basic:
    enabled: false

---

spring:
  profiles: cloud
  jpa:
    database: HSQL
